name: ci

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'readme.md'
  pull_request:

jobs:
  build:
    uses: xoofx/.github/.github/workflows/dotnet.yml@main
    with:
      runs-on: windows-latest
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}